---
title: "Algorithms and data structures"
subtitle: "Programming assignment 2 -  Doubly Linked List "
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Doubly Linked List

The purpose of this assignment is to make you familiar with implementing a data structure in Python in an object oriented way.
During the lectures, you were presented pseudo code of different basic data structures. Now we expect you to implement one of these structures yourself.

To make it clear what is needed, we will provide you with two classes: **Node** and **DoublyLinkedList**. The first one is already implemented (you don't need to modify it), the second one consist only a structure of empty methods defined. Your task is to come up with an implementation of these methods.

_Note_: If a list is doubly linked, each node contains a reference to the _previous_ node in the chain and a reference to the _next_ node.

An automated testing environment is used to validate your solution, this environment will test your solution against different datasets. To complete the assignment, every tests needs to be passed. If you are stuck or unsure why your solution fails, you can use the comment section on *Weblab* to ask for help.

You are expected to implement every function in DoublyLinkedList. Including the *next()* function, which is used by an iterator object in python. The *map(func)* function applies a function to every element in the list.
All other functions are available in the slides/book.

## Constructing a Doubly Linked List

The following code snippet is a constructor provided by the **DoublyLinkedList** Python class for the creation of a new doubly linked list.

```python
def __init__(self):
    self.__size = 0
    self.__header = Node('Header')
    self.__trailer = Node('Trailer')
    self.__header.set_next(self.__trailer)
    self.__trailer.set_previous(self.__header)
    self.__current = None
```

**T1 (5 points)**: Using the constructor from the **DoublyLinkedList**, create a new doubly linked list of random integers from 1 to 10.

## Using a Doubly Linked List

The given **DoublyLinkedList** Python class
contains helpful methods for using a doubly linked list.
Answer the following questions while implementing
the methods of the **DoublyLinkedList** class.

**T2 (10 points)**: Implement the `size` method that returns the size of a doubly linked list.

```python
def size(self):
  """Returns the number of elements in the list."""
  pass 
```

**T3 (5 points)**: Implement the `is_empty` method that checks
whether a doubly linked list is empty.

```python
def is_empty(self):
  """Returns the number of elements in the list"""
  pass
```

**T4 (10 points)**: Implement the methods `get_first` and `get_last`
to get the first and the last element of the list, respectively.

_Hint_: Return an exception in case the list is empty.

```python
def get_first(self):
  """Get the first element of the list"""
  pass

def get_last(self):
  """Get the last element of the list"""
  pass
```

**T5 (10 points)**: Implement the methods `get_previous` and `get_next`
to get the previous and the next node of the list, respectively.

_Hint_: Return an exception in case the list is empty.

```python
def get_previous(self, node):
  """Returns the node before the given node"""
  pass      

def get_next(self, node):
  """Returns the node after the given node"""
  pass
```

**T6 (10 points)**: Implement the methods `add_before` and `add_after`
to respectively insert new elements before and after a node of the list.

```python
def add_before(self, new, existing):
  """Insert the new before existing"""
  pass

def add_after(self, new, existing):
  """Insert the new after existing"""
  pass
```

**T7 (10 points)**: Implement the methods `add_first` and `add_first`
to respectively insert new nodes in the beginning and in the end of a list.

```python
def add_first(self, new):
  """Insert the node at the head of the list"""
  pass

def add_last(self, new):
  """Insert the node at the tail of the list"""
  pass
```

**T8 (10 points)**: Implement the method `remove` to remove
a node from a list.

```python
def remove(self, node):
  """Removes the given node from the list"""
  pass
```

**T9 (10 points)**: Implement the method `map` to apply a function on
each element of a list.

```python
def map(self, function):
  """Run function on every element in the list"""
  pass
```

**T10 (10 points)**: Implement the method `next` to iterate the elements
of a list.

```python
def next(self):
  """Standard python iterator method"""
  pass
```

## Applying methods of the DoublyLinkedList and Node classes

Answer the following questions by using
the implemented methods from the Node and DoublyLinkedList classes.
Apply your operations on the list you created in T1.

**T11 (5 points)**: Add 2 to each element of the list.

_Hint_: Use the methods `next`, `add_before`, and `add_after`.

**T12 (5 points)**: Multiply each element of the list by 5.

_Hint_: Use the methods `map`, `get_previous`, and `set_element`.

**T13 (5 points)**: Remove elements that are multiplied by 5.

_Hint_: Use the methods `next` and `remove`.

**T14 (5 points)**: Remove elements from the list that are odd numbers. 

_Hint_: Use the methods `get_previous` and `remove`.

## Proving performance properties

**T15 (5 points)**: Prove when the complexity to delete a node in a doubly linked list is $O(1)$
and $O(n)$.

### Sets

The following questions ask from you to apply set operations on elements.
Keep in mind that you should not use the ready *Sets* library of Python. 

**T16 (5 points)**: Given a list $L = [a, b, c, ...]$ you can create a set, $S$, of elements.
Implement a set constructor.

**T17 (5 points)**: Given two lists $L1 = [a1, b1, c1, ...]$ and $L2 = [a2, b2, c2, ...]$,
implement a $union$ method that returns to a new set $S$.

_Hint_: Use the constructor of a set you implemented in T16.

```python
def union():
  """Union of sets."""
  pass
```

**T18 (5 points)**: Given two lists $L1 = [a1, b1, c1, ...]$ and $L2 = [a2, b2, c2, ...]$,
implement a $diffence$ method that returns to a new set $S$.

_Hint_: Use the constructor of a set you implemented in T16.

```python
def difference():
  """Difference between sets."""
  pass
```

**T19 (5 points)**: Given two lists $L1 = [a1, b1, c1, ...]$ and $L2 = [a2, b2, c2, ...]$,
implement a $intersection$ method that returns to a new set $S$.

_Hint_: Use the constructor of a set you implemented in T16.

```python
def intersection():
  """Intersection between sets."""
  pass
```

### Dictionaries

A dictionary is an abstract data type
that represents a collection of (key, value) pairs.
Given two lists of elements, such as the following,
we can use a dictionary to reduce complexity
of searching for a specific element in the data structure.

**T20 (10 points)**: Implement a dictionary as a collection of (key, value) pairs.

_Hint_: You should not use the *dict* from Python.

$Names = [``Max", ``David", ``Sophie", ``Anne", ... ]$

$Grades = [``10", ``7", ``8", ``10", ... ]$
